@extends('errors.layout')
@section('title', __('পাওয়া যায়নি'))
@section('code', \App\Support\Lang::num(404))
@section('heading', __('এই লিংকে কিছু নেই 🧭'))
@section('message', __('লিংকটা হয়তো ভুল কপি হয়েছে। তবে নিজের বাংলাদেশ খুঁজে নিতে মাত্র ১ মিনিট লাগে!'))
