@extends('errors.layout')
@section('title', __('আবার চেষ্টা করো'))
@section('code', \App\Support\Lang::num(419))
@section('heading', __('পেজটা পুরোনো হয়ে গেছে'))
@section('message', __('অনেকক্ষণ খোলা ছিল। পেজটা রিফ্রেশ করে আবার চেষ্টা করো।'))
