@extends('errors.layout')
@section('title', __('একটু থামো'))
@section('code', \App\Support\Lang::num(429))
@section('heading', __('একটু বেশি তাড়াহুড়ো হয়ে গেল 😅'))
@section('message', __('এক মিনিট অপেক্ষা করে আবার চেষ্টা করো।'))
