@extends('errors.layout')
@section('title', __('সমস্যা হয়েছে'))
@section('code', \App\Support\Lang::num(500))
@section('heading', __('আমাদের দিকে একটা গোলমাল হয়েছে'))
@section('message', __('দুঃখিত! একটু পরে আবার চেষ্টা করো।'))
