@extends('errors.layout')
@section('title', __('একটু পরে আসো'))
@section('code', '')
@section('heading', __('একটু সাজিয়ে নিচ্ছি 🛠️'))
@section('message', __('কয়েক মিনিটের মধ্যেই ফিরে আসছি। একটু পরে আবার দেখো।'))
@section('noLink', true)
