"""
Builds resources/data/bd-districts.php: the 64 districts of Bangladesh as SVG paths in the same 400x552
viewBox and Mercator projection as resources/data/bd-divisions.php (the home map zooms into a division
and shows these), each with its bounding box and a label position (the centroid of its largest shape).

Source (public domain, CC0): geoBoundaries gbOpen BGD ADM2, simplified
https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/BGD/ADM2/geoBoundaries-BGD-ADM2_simplified.geojson

Usage: python3 -I scripts/build-district-map.py path/to/geoBoundaries-BGD-ADM2_simplified.geojson
"""
import json
import math
import sys

# lon/lat -> map %, the same fit as scripts/build-division-map.py
AX, BX = 21.010787, -1847.944113
AY, BY = -15.270579, 422.460205
# geoBoundaries names -> our area slugs where they differ from the lower-cased name
SLUGS = {
    'Barisal': 'barishal', 'Bogra': 'bogura', 'Brahamanbaria': 'brahmanbaria', 'Chittagong': 'chattogram',
    'Comilla': 'cumilla', "Cox's Bazar": 'coxs-bazar', 'Jessore': 'jashore', 'Maulvibazar': 'moulvibazar',
    'Nawabganj': 'chapai-nawabganj', 'Netrakona': 'netrokona',
}
MIN_AREA = 0.5  # svg units²: drops specks of islands
TOLERANCE = 0.4  # svg units: Douglas-Peucker; districts are seen zoomed in up to ~4x


def merc(lat):
    return math.degrees(math.log(math.tan(math.pi / 4 + math.radians(lat) / 2)))


def project(lon, lat):
    return ((AX * lon + BX) * 4, (AY * merc(lat) + BY) * 5.52)


def signed_area(ring):
    return sum(x1 * y2 - x2 * y1 for (x1, y1), (x2, y2) in zip(ring, ring[1:] + ring[:1])) / 2


def centroid(ring):
    a = signed_area(ring)
    cx = sum((x1 + x2) * (x1 * y2 - x2 * y1) for (x1, y1), (x2, y2) in zip(ring, ring[1:] + ring[:1]))
    cy = sum((y1 + y2) * (x1 * y2 - x2 * y1) for (x1, y1), (x2, y2) in zip(ring, ring[1:] + ring[:1]))
    return cx / (6 * a), cy / (6 * a)


def simplify(points, tol):
    if len(points) < 3:
        return points
    (x1, y1), (x2, y2) = points[0], points[-1]
    dx, dy = x2 - x1, y2 - y1
    norm = math.hypot(dx, dy) or 1e-9
    worst, index = 0, 0
    for i, (x, y) in enumerate(points[1:-1], 1):
        d = abs(dy * x - dx * y + x2 * y1 - y2 * x1) / norm
        if d > worst:
            worst, index = d, i
    if worst <= tol:
        return [points[0], points[-1]]
    return simplify(points[:index + 1], tol)[:-1] + simplify(points[index:], tol)


def simplify_ring(ring):
    # A closed ring starts and ends on the same point: split it at the point farthest from the start.
    if ring[0] == ring[-1]:
        ring = ring[:-1]
    far = max(range(len(ring)), key=lambda i: math.dist(ring[0], ring[i]))
    return simplify(ring[:far + 1], TOLERANCE)[:-1] + simplify(ring[far:] + [ring[0]], TOLERANCE)[:-1]


def build(polys):
    out, xs, ys, best = [], [], [], (0, None)
    for poly in polys:
        rings = [[project(*p) for p in ring] for ring in poly]
        size = abs(signed_area(rings[0]))
        if size < MIN_AREA:
            continue
        if size > best[0]:
            best = (size, centroid(rings[0]))
        for ring in rings:
            ring = simplify_ring(ring)
            pts = []
            for x, y in ring:
                pt = f'{x:.1f} {y:.1f}'
                if not pts or pts[-1] != pt:
                    pts.append(pt)
                xs.append(x)
                ys.append(y)
            if len(pts) >= 3:
                out.append('M' + 'L'.join(pts) + 'Z')
    box = [round(min(xs), 1), round(min(ys), 1), round(max(xs) - min(xs), 1), round(max(ys) - min(ys), 1)]
    return ''.join(out), box, [round(best[1][0], 1), round(best[1][1], 1)]


data = json.load(open(sys.argv[1]))
districts = {}
for f in data['features']:
    g = f['geometry']
    polys = g['coordinates'] if g['type'] == 'MultiPolygon' else [g['coordinates']]
    name = f['properties']['shapeName']
    districts[SLUGS.get(name, name.lower())] = build(polys)

with open('resources/data/bd-districts.php', 'w') as fh:
    fh.write('<?php\n\n// Generated by scripts/build-district-map.py from geoBoundaries (CC0). Do not edit by hand.\n')
    fh.write('// slug => [path, box [x, y, width, height], label [x, y]], in the 400x552 map viewBox.\n\nreturn [\n')
    for slug in sorted(districts):
        p, box, label = districts[slug]
        fh.write(f"    '{slug}' => ['{p}', {box}, {label}],\n")
    fh.write('];\n')
print(len(districts), 'districts,', sum(len(v[0]) for v in districts.values()), 'bytes of paths')
