"""
Builds resources/data/bd-divisions.php: the eight divisions of Bangladesh as SVG paths in the same
400x552 viewBox and Mercator projection as partials/bd-map (map % = a*lon + b, c*mercator(lat) + d,
fitted to the quiz places' positions; residuals < 0.1%).

Source (public domain, CC0): geoBoundaries gbOpen BGD ADM1, simplified
https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/BGD/ADM1/geoBoundaries-BGD-ADM1_simplified.geojson

Usage: python3 -I scripts/build-division-map.py path/to/geoBoundaries-BGD-ADM1_simplified.geojson
"""
import json
import math
import sys

# lon/lat -> map % (see app/Community/DivisionMap.php for the same fit used to place the spots)
AX, BX = 21.010787, -1847.944113
AY, BY = -15.270579, 422.460205
SLUGS = {
    'Barisal': 'barishal-division', 'Chittagong': 'chattogram-division', 'Dhaka': 'dhaka-division',
    'Khulna': 'khulna-division', 'Mymensingh': 'mymensingh-division', 'Rajshani': 'rajshahi-division',
    'Rajshahi': 'rajshahi-division', 'Rangpur': 'rangpur-division', 'Sylhet': 'sylhet-division',
}
MIN_AREA = 2.0  # svg units²: drops specks of islands that would only add noise


def merc(lat):
    return math.degrees(math.log(math.tan(math.pi / 4 + math.radians(lat) / 2)))


def project(lon, lat):
    return ((AX * lon + BX) * 4, (AY * merc(lat) + BY) * 5.52)


def area(ring):
    return abs(sum(x1 * y2 - x2 * y1 for (x1, y1), (x2, y2) in zip(ring, ring[1:] + ring[:1]))) / 2


def path(polys):
    out = []
    for poly in polys:
        rings = [[project(*p) for p in ring] for ring in poly]
        if area(rings[0]) < MIN_AREA:
            continue
        for ring in rings:
            pts = []
            for x, y in ring:
                pt = f'{x:.1f} {y:.1f}'
                if not pts or pts[-1] != pt:
                    pts.append(pt)
            out.append('M' + 'L'.join(pts) + 'Z')
    return ''.join(out)


data = json.load(open(sys.argv[1]))
paths = {}
for f in data['features']:
    g = f['geometry']
    polys = g['coordinates'] if g['type'] == 'MultiPolygon' else [g['coordinates']]
    paths[SLUGS[f['properties']['shapeName']]] = path(polys)

with open('resources/data/bd-divisions.php', 'w') as fh:
    fh.write('<?php\n\n// Generated by scripts/build-division-map.py from geoBoundaries (CC0). Do not edit by hand.\n\nreturn [\n')
    for slug in sorted(paths):
        fh.write(f"    '{slug}' => '{paths[slug]}',\n")
    fh.write('];\n')
print({k: len(v) for k, v in paths.items()}, sum(len(v) for v in paths.values()))
